version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - protoc -I proto/sso/ proto/sso/sso.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative
    sources:
      - proto/sso/sso.proto
    generates:
      - gen/go/sso.pb.go
      - gen/go/sso_grpc.pb.go